font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 12
env:
    TERM: xterm-256color
key_bindings:
    - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
    - { key: T,   mods: Control|Shift, action: SpawnNewInstance }
# Based on GNOME Terminal Tango Dark
colors:
  primary:
    #background: '0x2e3436'
    #foreground: '0xd3d7cf'
    background: '0x222222'
    foreground: '0xd3d7cf'
  normal:
    black: '0x2e3436'
    red: '0xcc0000'
    green: '0x4e9a06'
    yellow: '0xc4a000'
    blue: '0x3465a4'
    magenta: '0x75507b'
    cyan: '0x06989a'
    white: '0xd3d7cf'

  bright:
    black: '0x555753'
    red: '0xef2929'
    green: '0x8ae234'
    yellow: '0xfce94f'
    blue: '0x729fcf'
    magenta: '0xad7fa8'
    cyan: '0x34e2e2'
    white: '0xeeeeec'

