font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 12
env:
    TERM: xterm-256color
key_bindings:
    - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
    - { key: T,   mods: Control|Shift, action: SpawnNewInstance }

