#!/bin/bash

SANDBOX="/tmp/firefox-sandbox/"
mkdir -p $SANDBOX
mkdir -p $SANDBOX/.mozilla/firefox
TEMP_USER_PROFILE="`mktemp -d $SANDBOX/.mozilla/firefox/profile.pfox.tmp.XXXXXXXX`"
#google-chrome-stable \
#--no-first-run \
#--incognito \
#--proxy-server="socks5://localhost:1080" \
#--host-resolver-rules="MAP * 0.0.0.0" \
#--user-data-dir=$TEMP_USER_PROFILE \
#https://duckduckgo.com/

cat << EOF > $TEMP_USER_PROFILE/prefs.js
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 1080);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.type", 1);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("general.useragent.override", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:70.0) Gecko/20100101 Firefox/70.0");
#user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0");
EOF

#bwrap --bind / / --dev /dev --tmpfs /run --unshare-net firefox -profile $TEMP_USER_PROFILE -no-remote -private

#chmod -R 777 $SANDBOX
#firejail --noprofile --apparmor --seccomp --private=$SANDBOX firefox -profile $TEMP_USER_PROFILE -no-remote -private

#rm -rf $TEMP_USER_PROFILE

/usr/bin/uuidgen | /usr/bin/tr -d '-'  > $SANDBOX/machine-id


/usr/bin/bwrap \
    --ro-bind /lib /lib \
    --ro-bind /lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --bind /usr /usr \
    --proc /proc \
    --dev /dev \
    --ro-bind /bin /bin \
    --bind /tmp/firefox-sandbox/ /home/$USER \
    --uid 65534 --gid 65534 \
    --ro-bind $SANDBOX/machine-id /etc/machine-id \
    --share-net \
    --tmpfs /tmp \
    --dir /run/user/"$(id -u)" \
    --dev-bind /dev/dri /dev/dri \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    /usr/lib/firefox/firefox.sh  -profile `echo $TEMP_USER_PROFILE | sed "s|/tmp/firefox-sandbox/|$HOME|"` -no-remote -private
#
##    --unshare-net \
#    --bind $SANDBOX/.mozilla /home/r/.mozilla \
#    --uid `id -u nobody` --gid `id -g nobody` \
#    --bind $SANDBOX/Downloads /home/r/Downloads \
#    --bind / / \
#    --tmpfs /run \
#    --setenv HOME /home/user \
#    --unshare-user \

rm -rf $SANDBOX
